/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_leepood_capture_CaptureUtil */

#ifndef _Included_com_leepood_capture_CaptureUtil
#define _Included_com_leepood_capture_CaptureUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_leepood_capture_CaptureUtil
 * Method:    capture
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_leepood_capture_CaptureUtil_capture
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
